### ISSUE TITLE
planner drops aggregate expression without group by 

### ISSUE THREAD

**Issue by kszucs** [tobymao/sqlglot#747]
After running 

```py
expr = sg.parse_one(sqlstring)
tree = sgo.optimize(expr, catalog.to_sqlglot(), rules=sgo.RULES)
plan = sgp.Plan(tree)
print(plan.root)
```

on the following SQL query:

```sql
SELECT AVG("star1"."f") AS "mean" FROM star1
```

I'm getting:

```
    - Scan: star1
        Context:
        Source: "star1" AS "star1"
        Projections:
        - "star1"."mean"
```

where the projection doesn't hold the avg expression.

**Comment by tobymao** [comment]
will look at this one soon

**Comment by tobymao** [comment]
i don't see any issues with this on main.

```
        result = execute("SELECT AVG(star1.f) AS MEAN FROM star1", tables={"star1": [{"f": 1}, {"f": 2}]})
        print(result)
```

```
- Aggregate: star1 (140060816954544)
    Context:
      Aggregations:
        - AVG("star1"."f") AS "MEAN"
    Projections:
      - "star1"."MEAN"
    Dependencies:
    - Scan: star1 (140060816954496)
      Context:
        Source: "star1" AS "star1"
      Projections:
MEAN
 1.5
```
