### ISSUE TITLE
planner ignores subqueries

### ISSUE THREAD

**Issue by kszucs** [tobymao/sqlglot#748]
```sql
SELECT *
FROM star1
WHERE `f` > (
  SELECT avg(`f`) AS `mean`
  FROM star1
)
```

output plan after 

```py
expr = sg.parse_one(sqlstring, dialect)
tree = sgo.optimize(expr, catalog.to_sqlglot(), rules=sgo.RULES)
plan = sgp.Plan(tree)
print(plan.root)
```

```
- Scan: star1
    Context:
      Source: "star1" AS "star1"
    Projections:
      - "star1"."c" AS "c"
      - "star1"."f" AS "f"
      - "star1"."foo_id" AS "foo_id"
      - "star1"."bar_id" AS "bar_id"
    Condition: "star1"."f" > (SELECT AVG("star1"."f") AS "mean" FROM "star1" AS "star1")
```

I'd expect the select to be converted as an aggregate dependency of the root scan.
