### ISSUE TITLE
DISTINCT omitted in the planner output

### ISSUE THREAD

**Issue by kszucs** [tobymao/sqlglot#781]
For the following SQL query:

```sql
SELECT DISTINCT first_name FROM employee
```

The planner gives the following output:

```
- Scan: employee (5606700320)
    Context:
      Source: "employee" AS "employee"
    Projections:
      - "employee"."first_name" AS "first_name"
```

`sqlglot` version: `10.1.0`
